server:
  port: 8088
spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nacos_provider
          uri: lb://nacos-provider
          predicates:
            - Path=/provide/**
        - id: nacos_customer
          uri: lb://nacos-customer
          predicates:
            - Path=/customer/**
        - id: oauth2_demo
          uri: lb://oauth2-demo
          predicates:
            - Path=/oauth/**
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 1.13.17.66:8848
        username: nacos
#    sentinel:
#      transport:
#        dashboard: 1.13.17.66:8080
#        port: 8719
  main:
    allow-bean-definition-overriding: true

oauth2:
  cloud:
    sys:
      parameter:
        ignoreUrls:
          - /oauth/token
          - /oauth/authorize
          - /oauth/check_token
          - /login
