server:
    port: 8840
spring:
    application:
        name: nacos-config
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: 1.13.17.66:8848
                username: nacos
