spring:
    application:
        name: oauth2-demo
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: 1.13.17.66:8848
                username: nacos
server:
    port: 8844
log:
    path: /home/cloud-demo/oauth-demo

logging:
    level:
        com.qq: debug